modLoader = "javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL = "https://github.com/midnight1201/clean-n-cleanse/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://modrinth.com/mod/clean-n-cleanse"
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = "icon.png"

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "create"
type = "required"
versionRange = "[6.0.9,6.1.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "jei"
type = "optional"
versionRange = "[19,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "vanillabackport"
type = "optional"
reason = "Versions before 1.1.7 don't add sulfur blocks!"
versionRange = "[1.1.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "create_sa"
type = "optional"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "create_aquatic_ambitions"
type = "optional"
ordering = "AFTER"
side = "BOTH"
